version: "3.9"

services:
    https-portal:
        image: steveltn/https-portal:1.3.0
        ports:
        - '80:80'
        - '443:443'
        depends_on:
        - viz-service
        - browse-service
        - logging-service
        volumes:
            - https-portal-data:/var/lib/https-portal        
        restart: always
        environment:
            DOMAINS: 'viz.portal.cssat.org -> http://viz-service, portal.cssat.org -> http://browse-service'
            STAGE: 'local'        
            # Don't output logs with status code 2XX to stdout
            FLUENTD_STDOUT_FILTER_PATTERN: '\A[^ ]* [^ ]* [^ ] \[[^\]]*\] "\S+(?: +[^\"]*?(?: +\S*)?)?" 2'
        logging:
            driver: fluentd
            options:
                fluentd-address: docker.for.mac.localhost:24224
                fluentd-sub-second-precision: "true"
                tag: docker.https-portal
                env: FLUENTD_STDOUT_FILTER_PATTERN       
        links: 
            - logging-service              
    viz-service:
        build: 
            context: .
            dockerfile: ./viz-service/Dockerfile      
        depends_on:
            - logging-service
        volumes:
            - ./viz-service/html:/portal-visualizations/  
            - ./common-resources/:/portal-visualizations/public/content-data/            
        environment:
            MYSQL_DATABASE: annie
            MYSQL_USER: annie
            MYSQL_PASSWORD: 'b4Rxx:pW'
            MYSQL_HOST: "annie.criploulbgnu.us-west-2.rds.amazonaws.com"
            MYSQL_PORT: 3306
            CONTENT_PATH: './content-data/content/graphs/'
            VIRTUAL_HOST: viz.portal.cssat.org
            # Don't output logs with status code 2XX to stdout
            FLUENTD_STDOUT_FILTER_PATTERN: '\A[^ ]* [^ ]* [^ ] \[[^\]]*\] "\S+(?: +[^\"]*?(?: +\S*)?)?" 2'
        logging:
            driver: fluentd
            options:
                fluentd-address: docker.for.mac.localhost:24224
                fluentd-sub-second-precision: "true"
                tag: docker.viz-service
                env: FLUENTD_STDOUT_FILTER_PATTERN         
        links: 
            - logging-service            
    browse-service:
        build: 
            context: .
            dockerfile: ./browse-service/Dockerfile      
        depends_on:
            - logging-service
        volumes:
            - ./browse-service/html:/portal-browse/  
            - ./common-resources/:/portal-browse/public/content-data/         
        environment:
            VIRTUAL_HOST: portal.cssat.org
            # Don't output logs with status code 2XX to stdout
            FLUENTD_STDOUT_FILTER_PATTERN: '\A[^ ]* [^ ]* [^ ] \[[^\]]*\] "\S+(?: +[^\"]*?(?: +\S*)?)?" 2'
        logging:
            driver: fluentd
            options:
                fluentd-address: docker.for.mac.localhost:24224
                fluentd-sub-second-precision: "true"
                tag: docker.browse-service
                env: FLUENTD_STDOUT_FILTER_PATTERN      
        links: 
            - logging-service      
    test-service: 
        build: 
            context: .
            dockerfile: ./test-service/Dockerfile      
        volumes: 
            - ./test-service/unit/phpunit/:/app/tests
            - ./browse-service/:/app/browse-service
            - ./viz-service/:/app/viz-service         
        stdin_open: true # docker run -i
        tty: true        # docker run -t
    logging-service:
        build: 
            context: ./logging-service
            dockerfile: Dockerfile
        env_file:
            ./logging-service/.env
        ports:
            - '24224:24224'
volumes:
    https-portal-data:
