version: "3.9"

services:
    https-portal:
        image: steveltn/https-portal:1.3.0
        ports:
        - '80:80'
        - '443:443'
        depends_on:
        - viz-service
        - browse-service
        - logging-service
        volumes:
            - https-portal-data:/var/lib/https-portal        
        restart: always
        environment:
            DOMAINS: 'viz.portal.cssat.org -> http://viz-service, portal.cssat.org -> http://browse-service'
            STAGE: 'local'        
            # Don't output logs with status code 2XX to stdout
            FLUENTD_STDOUT_FILTER_PATTERN: '\A[^ ]* [^ ]* [^ ] \[[^\]]*\] "\S+(?: +[^\"]*?(?: +\S*)?)?" 2'
        logging:
            driver: fluentd
            options:
                fluentd-address: 172.20.0.6:24224
                fluentd-sub-second-precision: "true"
                fluentd-async-connect: "true"
                fluentd-retry-wait: 1s
                fluentd-max-retries: 30
                tag: docker.https-portal
                env: FLUENTD_STDOUT_FILTER_PATTERN       
        # links: 
        #     - logging-service         
        networks:
            viz: 
                ipv4_address: 172.20.0.2                   
    viz-service:
        env_file:
            ./viz-service/.env    
        build: 
            context: .
            dockerfile: ./viz-service/Dockerfile      
        depends_on:
            - logging-service
        networks:
            viz: 
                ipv4_address: 172.20.0.3       
        volumes:
            - ./viz-service/html:/portal-visualizations/  
            - ./common-resources/:/portal-visualizations/public/content-data/            
        environment:
            CONTENT_PATH: './content-data/content/graphs/'
            VIRTUAL_HOST: viz.portal.cssat.org
            VIRTUAL_HOST_ROOT: portal-visualizations
            # Don't output logs with status code 2XX to stdout
            FLUENTD_STDOUT_FILTER_PATTERN: '\A[^ ]* [^ ]* [^ ] \[[^\]]*\] "\S+(?: +[^\"]*?(?: +\S*)?)?" 2'
        logging:
            driver: fluentd
            options:
                fluentd-address: 172.20.0.6:24224
                fluentd-sub-second-precision: "true"
                fluentd-async-connect: "true"
                fluentd-retry-wait: 1s
                fluentd-max-retries: 30
                tag: docker.viz-service
                env: FLUENTD_STDOUT_FILTER_PATTERN         
        # links: 
        #     - logging-service            
    browse-service:
        build: 
            context: .
            dockerfile: ./browse-service/Dockerfile      
        depends_on:
            - logging-service        
        volumes:
            - ./browse-service/html:/portal-browse/  
            - ./common-resources/:/portal-browse/public/content-data/         
        environment:
            VIRTUAL_HOST: portal.cssat.org
            VIRTUAL_HOST_ROOT: portal-browse            
            # Don't output logs with status code 2XX to stdout
            FLUENTD_STDOUT_FILTER_PATTERN: '\A[^ ]* [^ ]* [^ ] \[[^\]]*\] "\S+(?: +[^\"]*?(?: +\S*)?)?" 2'
        logging:
            driver: fluentd
            options:
                fluentd-address: 172.20.0.6:24224
                fluentd-sub-second-precision: "true"
                fluentd-async-connect: "true"
                fluentd-retry-wait: 1s
                fluentd-max-retries: 30
                tag: docker.browse-service
                env: FLUENTD_STDOUT_FILTER_PATTERN      
        # links: 
        #     - logging-service   
        networks:
            viz: 
                ipv4_address: 172.20.0.4                             
    logging-service:
        build: 
            context: ./logging-service
            dockerfile: Dockerfile
        env_file:
            ./logging-service/.env
        ports:
            - '24224:24224'
        networks:
            viz: 
                ipv4_address: 172.20.0.6                

volumes:
    https-portal-data:

networks:
  viz:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
